// <auto-generated />
using ERP_Anass_backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_Anass_backend.Migrations
{
    [DbContext(typeof(DbContextERP))]
    [Migration("20240915173709_adduserstable")]
    partial class adduserstable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ERP_Anass_backend.Models.Article", b =>
                {
                    b.Property<int>("idArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idArticle"));

                    b.Property<string>("ArticleName")
                        .HasColumnType("longtext");

                    b.Property<string>("ArticleRef")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionArticle")
                        .HasColumnType("longtext");

                    b.Property<int>("FamilyID")
                        .HasColumnType("int");

                    b.Property<float>("PurchasePrice")
                        .HasColumnType("float");

                    b.Property<float>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("idArticle");

                    b.HasIndex("FamilyID");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Familly", b =>
                {
                    b.Property<int>("idFamilly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idFamilly"));

                    b.Property<string>("familyDesc")
                        .HasColumnType("longtext");

                    b.Property<string>("familyName")
                        .HasColumnType("longtext");

                    b.Property<string>("familyRef")
                        .HasColumnType("longtext");

                    b.HasKey("idFamilly");

                    b.ToTable("Familly");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<float>("CreatedAt")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<float>("Password")
                        .HasColumnType("float");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<float>("Status")
                        .HasColumnType("float");

                    b.Property<float>("UpdatedAt")
                        .HasColumnType("float");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Article", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Familly", "Familly")
                        .WithMany("Article")
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Familly");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Familly", b =>
                {
                    b.Navigation("Article");
                });
#pragma warning restore 612, 618
        }
    }
}
