// <auto-generated />
using System;
using ERP_Anass_backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_Anass_backend.Migrations
{
    [DbContext(typeof(DbContextERP))]
    [Migration("20250313204001_addBrandArticleRelation")]
    partial class addBrandArticleRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ERP_Anass_backend.Models.Article", b =>
                {
                    b.Property<int>("idArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idArticle"));

                    b.Property<string>("ArticleName")
                        .HasColumnType("longtext");

                    b.Property<string>("ArticleRef")
                        .HasColumnType("longtext");

                    b.Property<int?>("BrandID")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionArticle")
                        .HasColumnType("longtext");

                    b.Property<int>("FamilyID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("PurchasePrice")
                        .HasColumnType("float");

                    b.Property<float>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("idArticle");

                    b.HasIndex("BrandID");

                    b.HasIndex("FamilyID");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("BrandName")
                        .HasColumnType("longtext");

                    b.Property<string>("BrandRef")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("idFamilly")
                        .HasColumnType("int");

                    b.HasKey("BrandID");

                    b.HasIndex("idFamilly");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CityID"));

                    b.Property<string>("CityName")
                        .HasColumnType("longtext");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("zipCode")
                        .HasColumnType("int");

                    b.HasKey("CityID");

                    b.HasIndex("CountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .HasColumnType("longtext");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Currency", b =>
                {
                    b.Property<int>("IdCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCurrency"));

                    b.Property<string>("CurrencyName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdCurrency");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorksID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryId");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("WorksID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Familly", b =>
                {
                    b.Property<int>("idFamilly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idFamilly"));

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("familyDesc")
                        .HasColumnType("longtext");

                    b.Property<string>("familyName")
                        .HasColumnType("longtext");

                    b.Property<string>("familyRef")
                        .HasColumnType("longtext");

                    b.HasKey("idFamilly");

                    b.ToTable("Familly");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Modules", b =>
                {
                    b.Property<int>("IdModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdModule"));

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModuleName")
                        .HasColumnType("longtext");

                    b.HasKey("IdModule");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Permission", b =>
                {
                    b.Property<int>("IdPermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPermission"));

                    b.Property<bool>("Add")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Edit")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdModule")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("IdPermission");

                    b.HasIndex("IdModule");

                    b.HasIndex("UserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Purchase", b =>
                {
                    b.Property<int>("IdPurchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPurchase"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCurrency")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PurchaseRef")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idSupplier")
                        .HasColumnType("int");

                    b.HasKey("IdPurchase");

                    b.HasIndex("IdCurrency");

                    b.HasIndex("idSupplier");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.PurchaseDetails", b =>
                {
                    b.Property<int>("IdPurchaseDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPurchaseDetails"));

                    b.Property<int>("IdPurchase")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Quality")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("idArticle")
                        .HasColumnType("int");

                    b.HasKey("IdPurchaseDetails");

                    b.HasIndex("IdPurchase");

                    b.HasIndex("idArticle");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Supplier", b =>
                {
                    b.Property<int>("idSupplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idSupplier"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("longtext");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierName")
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierRef")
                        .HasColumnType("longtext");

                    b.HasKey("idSupplier");

                    b.HasIndex("CountryId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Works", b =>
                {
                    b.Property<int>("WorkstID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkstID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("WorksName")
                        .HasColumnType("longtext");

                    b.HasKey("WorkstID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Article", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Brand", "Brand")
                        .WithMany("Article")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("ERP_Anass_backend.Models.Familly", "Familly")
                        .WithMany("Article")
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Familly");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Brand", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Familly", "Familly")
                        .WithMany("Brand")
                        .HasForeignKey("idFamilly")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Familly");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.City", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Country", "Country")
                        .WithMany("City")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Employee", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.City", "City")
                        .WithMany("Employees")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ERP_Anass_backend.Models.Country", "Country")
                        .WithMany("Employees")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ERP_Anass_backend.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ERP_Anass_backend.Models.Works", "Works")
                        .WithMany("Employees")
                        .HasForeignKey("WorksID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Department");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Permission", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Modules", "Modules")
                        .WithMany("Permission")
                        .HasForeignKey("IdModule")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ERP_Anass_backend.Models.User", "User")
                        .WithMany("Permission")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Modules");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Purchase", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Currency", "Currencyobj")
                        .WithMany("Purchases")
                        .HasForeignKey("IdCurrency")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ERP_Anass_backend.Models.Supplier", "Supplier")
                        .WithMany("Purchase")
                        .HasForeignKey("idSupplier")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Currencyobj");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.PurchaseDetails", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Purchase", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("IdPurchase")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ERP_Anass_backend.Models.Article", "Article")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("idArticle")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Supplier", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Country", "Country")
                        .WithMany("Supplier")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Works", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Department", "Department")
                        .WithMany("Work")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Article", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Brand", b =>
                {
                    b.Navigation("Article");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.City", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Country", b =>
                {
                    b.Navigation("City");

                    b.Navigation("Employees");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Currency", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Familly", b =>
                {
                    b.Navigation("Article");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Modules", b =>
                {
                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Supplier", b =>
                {
                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.User", b =>
                {
                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Works", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
