// <auto-generated />
using System;
using ERP_Anass_backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_Anass_backend.Migrations
{
    [DbContext(typeof(DbContextERP))]
    [Migration("20260123201004_AddInvoiceAndBanking")]
    partial class AddInvoiceAndBanking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ERP_Anass_backend.Models.Account", b =>
                {
                    b.Property<int>("idAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idAccount"));

                    b.Property<string>("AccountCode")
                        .HasColumnType("longtext");

                    b.Property<string>("AccountName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("idAccount");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.AppConfiguration", b =>
                {
                    b.Property<int>("idAppConfiguration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idAppConfiguration"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("idAppConfiguration");

                    b.ToTable("AppConfigurations");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Article", b =>
                {
                    b.Property<int>("idArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idArticle"));

                    b.Property<string>("ArticleName")
                        .HasColumnType("longtext");

                    b.Property<string>("ArticleRef")
                        .HasColumnType("longtext");

                    b.Property<int?>("BrandID")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionArticle")
                        .HasColumnType("longtext");

                    b.Property<int?>("FamilyID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("PurchasePrice")
                        .HasColumnType("float");

                    b.Property<float>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("idIncomeAccount")
                        .HasColumnType("int");

                    b.Property<int>("idInventoryAccount")
                        .HasColumnType("int");

                    b.HasKey("idArticle");

                    b.HasIndex("BrandID");

                    b.HasIndex("FamilyID");

                    b.HasIndex("idIncomeAccount");

                    b.HasIndex("idInventoryAccount");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.BankAccount", b =>
                {
                    b.Property<int>("idBankAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idBankAccount"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("BankName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("IBAN")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idBankAccount");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.BillOfMaterials", b =>
                {
                    b.Property<int>("idBOM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idBOM"));

                    b.Property<int>("ChildArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParentArticleId")
                        .HasColumnType("int");

                    b.Property<float>("QuantityNeeded")
                        .HasColumnType("float");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idBOM");

                    b.HasIndex("ChildArticleId");

                    b.HasIndex("ParentArticleId");

                    b.ToTable("BillOfMaterials");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("BrandName")
                        .HasColumnType("longtext");

                    b.Property<string>("BrandRef")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("idFamilly")
                        .HasColumnType("int");

                    b.HasKey("BrandID");

                    b.HasIndex("idFamilly");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CityID"));

                    b.Property<string>("CityName")
                        .HasColumnType("longtext");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("zipCode")
                        .HasColumnType("int");

                    b.HasKey("CityID");

                    b.HasIndex("CountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Currency", b =>
                {
                    b.Property<int>("IdCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCurrency"));

                    b.Property<string>("CurrencyName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdCurrency");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Customer", b =>
                {
                    b.Property<int>("idCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCustomer"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("longtext");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerRef")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int?>("idControlAccount")
                        .HasColumnType("int");

                    b.HasKey("idCustomer");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryId");

                    b.HasIndex("idControlAccount");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WorksID")
                        .HasColumnType("int");

                    b.Property<int?>("idExpenseAccount")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryId");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("WorksID");

                    b.HasIndex("idExpenseAccount");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Familly", b =>
                {
                    b.Property<int>("idFamilly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idFamilly"));

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("familyDesc")
                        .HasColumnType("longtext");

                    b.Property<string>("familyName")
                        .HasColumnType("longtext");

                    b.Property<string>("familyRef")
                        .HasColumnType("longtext");

                    b.HasKey("idFamilly");

                    b.ToTable("Familly");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Invoice", b =>
                {
                    b.Property<int>("idInvoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idInvoice"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("InvoiceType")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idInvoice");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("SaleId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.InvoiceDetails", b =>
                {
                    b.Property<int>("idInvoiceDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idInvoiceDetail"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idInvoiceDetail");

                    b.HasIndex("ArticleId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.JournalDetails", b =>
                {
                    b.Property<int>("idJournalDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idJournalDetails"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("CreditAmount")
                        .HasColumnType("float");

                    b.Property<float>("DebitAmount")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("JournalEntryID")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idJournalDetails");

                    b.HasIndex("AccountID");

                    b.HasIndex("JournalEntryID");

                    b.ToTable("JournalDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.JournalEntry", b =>
                {
                    b.Property<int>("idJournalEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idJournalEntry"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<float>("TotalCredit")
                        .HasColumnType("float");

                    b.Property<float>("TotalDebit")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idJournalEntry");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.ModuleLicense", b =>
                {
                    b.Property<int>("idModuleLicense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idModuleLicense"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLicensed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModuleName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idModuleLicense");

                    b.ToTable("ModuleLicenses");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Modules", b =>
                {
                    b.Property<int>("IdModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdModule"));

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModuleName")
                        .HasColumnType("longtext");

                    b.HasKey("IdModule");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Payment", b =>
                {
                    b.Property<int>("idPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idPayment"));

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.Property<int?>("idBankAccount")
                        .HasColumnType("int");

                    b.Property<int?>("idCashAccount")
                        .HasColumnType("int");

                    b.HasKey("idPayment");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("SaleId");

                    b.HasIndex("idBankAccount");

                    b.HasIndex("idCashAccount");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Permission", b =>
                {
                    b.Property<int>("IdPermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPermission"));

                    b.Property<bool>("Add")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Edit")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IdModule")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("IdPermission");

                    b.HasIndex("IdModule");

                    b.HasIndex("UserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Purchase", b =>
                {
                    b.Property<int>("IdPurchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPurchase"));

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCurrency")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("longtext");

                    b.Property<string>("PurchaseChannel")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PurchaseRef")
                        .HasColumnType("longtext");

                    b.Property<string>("PurchaseStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("PurchaseType")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ShippingAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalPayment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalTaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("idSupplier")
                        .HasColumnType("int");

                    b.HasKey("IdPurchase");

                    b.HasIndex("IdCurrency");

                    b.HasIndex("idSupplier");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.PurchaseDetails", b =>
                {
                    b.Property<int>("IdPurchaseDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPurchaseDetails"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdPurchase")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("LineDiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("LineDiscountPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LineItemStatus")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("LineTaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Quality")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ReceivedQuantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("RejectedQuantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("WarehouseLocation")
                        .HasColumnType("longtext");

                    b.Property<int?>("idArticle")
                        .HasColumnType("int");

                    b.HasKey("IdPurchaseDetails");

                    b.HasIndex("IdPurchase");

                    b.HasIndex("idArticle");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Sale", b =>
                {
                    b.Property<int>("IdSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSale"));

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCurrency")
                        .HasColumnType("int");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("SaleChannel")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SaleRef")
                        .HasColumnType("longtext");

                    b.Property<string>("SaleStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("SaleType")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ShippingAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalPayment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalTaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdSale");

                    b.HasIndex("IdCurrency");

                    b.HasIndex("IdCustomer");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.SaleDetails", b =>
                {
                    b.Property<int>("IdSaleDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSaleDetails"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdSale")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("LineDiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("LineDiscountPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LineItemStatus")
                        .HasColumnType("longtext");

                    b.Property<decimal>("LineTaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Quality")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RejectedQuantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("longtext");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("WarehouseLocation")
                        .HasColumnType("longtext");

                    b.Property<int?>("idArticle")
                        .HasColumnType("int");

                    b.HasKey("IdSaleDetails");

                    b.HasIndex("IdSale");

                    b.HasIndex("idArticle");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.StockMovement", b =>
                {
                    b.Property<int>("idStockMovement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idStockMovement"));

                    b.Property<int>("ArticleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int");

                    b.HasKey("idStockMovement");

                    b.HasIndex("ArticleID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Supplier", b =>
                {
                    b.Property<int>("idSupplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idSupplier"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("longtext");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierName")
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierRef")
                        .HasColumnType("longtext");

                    b.Property<int?>("idControlAccount")
                        .HasColumnType("int");

                    b.HasKey("idSupplier");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryId");

                    b.HasIndex("idControlAccount");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Tenant", b =>
                {
                    b.Property<Guid>("idTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Domain")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("idTenant");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("idUom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idUom"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UomName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idUom");

                    b.ToTable("UnitOfMeasures");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Warehouse", b =>
                {
                    b.Property<int>("idWarehouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idWarehouse"));

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("idWarehouse");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Works", b =>
                {
                    b.Property<int>("WorkstID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkstID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcitve")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("WorksName")
                        .HasColumnType("longtext");

                    b.HasKey("WorkstID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Article", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Brand", "Brand")
                        .WithMany("Article")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Article_Brand_BrandID");

                    b.HasOne("ERP_Anass_backend.Models.Familly", "Familly")
                        .WithMany("Article")
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Article_Familly_FamilyID");

                    b.HasOne("ERP_Anass_backend.Models.Account", "IncomeAccount")
                        .WithMany()
                        .HasForeignKey("idIncomeAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_Anass_backend.Models.Account", "InventoryAccount")
                        .WithMany()
                        .HasForeignKey("idInventoryAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Familly");

                    b.Navigation("IncomeAccount");

                    b.Navigation("InventoryAccount");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.BillOfMaterials", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Article", "ChildArticle")
                        .WithMany()
                        .HasForeignKey("ChildArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_Anass_backend.Models.Article", "ParentArticle")
                        .WithMany()
                        .HasForeignKey("ParentArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildArticle");

                    b.Navigation("ParentArticle");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Brand", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Familly", "Familly")
                        .WithMany("Brand")
                        .HasForeignKey("idFamilly");

                    b.Navigation("Familly");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.City", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Country", "Country")
                        .WithMany("City")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Customer", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.City", "City")
                        .WithMany("Customer")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Country", "Country")
                        .WithMany("Customer")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Account", "ControlAccount")
                        .WithMany()
                        .HasForeignKey("idControlAccount")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("ControlAccount");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Employee", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.City", "City")
                        .WithMany("Employees")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Country", "Country")
                        .WithMany("Employees")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Works", "Works")
                        .WithMany("Employees")
                        .HasForeignKey("WorksID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Account", "ExpenseAccount")
                        .WithMany()
                        .HasForeignKey("idExpenseAccount")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Department");

                    b.Navigation("ExpenseAccount");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Invoice", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_Anass_backend.Models.Purchase", "Purchase")
                        .WithMany()
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_Anass_backend.Models.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_Anass_backend.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Purchase");

                    b.Navigation("Sale");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.InvoiceDetails", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_Anass_backend.Models.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.JournalDetails", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_Anass_backend.Models.JournalEntry", "JournalEntry")
                        .WithMany("JournalDetails")
                        .HasForeignKey("JournalEntryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Payment", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Purchase", "Purchase")
                        .WithMany()
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_Anass_backend.Models.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP_Anass_backend.Models.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("idBankAccount");

                    b.HasOne("ERP_Anass_backend.Models.Account", "CashAccount")
                        .WithMany()
                        .HasForeignKey("idCashAccount")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BankAccount");

                    b.Navigation("CashAccount");

                    b.Navigation("Purchase");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Permission", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Modules", "Modules")
                        .WithMany("Permission")
                        .HasForeignKey("IdModule")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.User", "User")
                        .WithMany("Permission")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Modules");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Purchase", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Currency", "Currencyobj")
                        .WithMany("Purchases")
                        .HasForeignKey("IdCurrency")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Supplier", "Supplier")
                        .WithMany("Purchase")
                        .HasForeignKey("idSupplier")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Currencyobj");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.PurchaseDetails", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Purchase", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("IdPurchase")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Article", "Article")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("idArticle")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Article");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Sale", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Currency", "Currencyobj")
                        .WithMany("Sales")
                        .HasForeignKey("IdCurrency")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Customer", "Customerobj")
                        .WithMany("Sales")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Currencyobj");

                    b.Navigation("Customerobj");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.SaleDetails", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("IdSale")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Article", "Article")
                        .WithMany("SaleDetails")
                        .HasForeignKey("idArticle")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Article");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.StockMovement", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP_Anass_backend.Models.Warehouse", "Warehouse")
                        .WithMany("StockMovements")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Supplier", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.City", "City")
                        .WithMany("Supplier")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Country", "Country")
                        .WithMany("Supplier")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP_Anass_backend.Models.Account", "ControlAccount")
                        .WithMany()
                        .HasForeignKey("idControlAccount")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("ControlAccount");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Works", b =>
                {
                    b.HasOne("ERP_Anass_backend.Models.Department", "Department")
                        .WithMany("Work")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Article", b =>
                {
                    b.Navigation("PurchaseDetails");

                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Brand", b =>
                {
                    b.Navigation("Article");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.City", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Employees");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Country", b =>
                {
                    b.Navigation("City");

                    b.Navigation("Customer");

                    b.Navigation("Employees");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Currency", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Familly", b =>
                {
                    b.Navigation("Article");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.JournalEntry", b =>
                {
                    b.Navigation("JournalDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Modules", b =>
                {
                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Supplier", b =>
                {
                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.User", b =>
                {
                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Warehouse", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("ERP_Anass_backend.Models.Works", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
